server:
  port: 8082

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/flight_ticket"
    username: root
    password:
#  logging:
#    level:
#      org:
#        springframework:
#          security: DEBUG
